/**
 * Launch Control Configuration
 * Real-time platform controls and risk management
 */

const DEFAULT_LAUNCH_CONTROLS = {
  // Capacity Limits
  MAX_DAILY_ORDERS: 1000,
  MAX_ACTIVE_RETAILERS: 100,
  MAX_ACTIVE_VENDORS: 50,
  MAX_CONCURRENT_ORDERS: 200,
  
  // Risk Controls
  MAX_CREDIT_PER_RETAILER: 50000, // in cents
  MAX_ORDER_VALUE: 100000, // in cents
  CREDIT_UTILIZATION_THRESHOLD: 0.8,
  
  // Feature Flags
  ENABLE_NEW_RETAILER_SIGNUP: true,
  ENABLE_VENDOR_BIDDING: true,
  ENABLE_CREDIT_SYSTEM: true,
  ENABLE_AUTO_ROUTING: true,
  
  // Admin Controls
  ADMIN_APPROVAL_REQUIRED: false,
  MANUAL_ORDER_REVIEW_THRESHOLD: 50000, // in cents
  
  // Emergency Controls
  EMERGENCY_STOP: false,
  MAINTENANCE_MODE: false,
  READ_ONLY_MODE: false,
  
  // Performance Controls
  RATE_LIMIT_PER_MINUTE: 60,
  MAX_WEBHOOK_RETRIES: 3,
  ORDER_TIMEOUT_MINUTES: 30
};

const LAUNCH_CONTROL_PRESETS = {
  SOFT_LAUNCH: {
    MAX_DAILY_ORDERS: 50,
    MAX_ACTIVE_RETAILERS: 10,
    MAX_ACTIVE_VENDORS: 5,
    ADMIN_APPROVAL_REQUIRED: true,
    ENABLE_NEW_RETAILER_SIGNUP: false
  },
  
  BETA_LAUNCH: {
    MAX_DAILY_ORDERS: 200,
    MAX_ACTIVE_RETAILERS: 25,
    MAX_ACTIVE_VENDORS: 15,
    ADMIN_APPROVAL_REQUIRED: true,
    ENABLE_NEW_RETAILER_SIGNUP: true
  },
  
  FULL_LAUNCH: {
    MAX_DAILY_ORDERS: 1000,
    MAX_ACTIVE_RETAILERS: 100,
    MAX_ACTIVE_VENDORS: 50,
    ADMIN_APPROVAL_REQUIRED: false,
    ENABLE_NEW_RETAILER_SIGNUP: true
  },
  
  EMERGENCY_LOCKDOWN: {
    EMERGENCY_STOP: true,
    ENABLE_NEW_RETAILER_SIGNUP: false,
    ENABLE_VENDOR_BIDDING: false,
    READ_ONLY_MODE: true
  }
};

module.exports = {
  DEFAULT_LAUNCH_CONTROLS,
  LAUNCH_CONTROL_PRESETS
};